version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_DATABASE: hacknow
    ports:
      - "3308:3306"
    # security_opt:
    #   - seccomp:unconfined